name: humble
on:
  push:
    branches:
      - 'main'
      - 'humble'
  pull_request:
    branches:
      - 'main'
      - 'humble'
  workflow_dispatch:
    branches:
      - '*'
jobs:
  ros_humble:
    name: humble
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - name: Setup ROS humble
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@0.3.13
        with:
          target-ros2-distro: humble
          vcs-repo-file-url: $GITHUB_WORKSPACE/source_dependencies.yaml
          rosdep-check: true
