name: jazzy
on:
  push:
    branches:
      - 'main'
      - 'jazzy'
  pull_request:
    branches:
      - 'main'
      - 'jazzy'
  workflow_dispatch:
    branches:
      - '*'
jobs:
  ros_jazzy:
    name: jazzy
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Setup ROS jazzy
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@0.4.5
        with:
          target-ros2-distro: jazzy
          vcs-repo-file-url: $GITHUB_WORKSPACE/source_dependencies.yaml
          rosdep-check: true